// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyDRlwKjKLPypJkF4W5c-ZPtgJG11bJIM',
    appId: '1:354444862050:web:2db670de1d732174a8a73b',
    messagingSenderId: '354444862050',
    projectId: 'moviles2-e13d3',
    authDomain: 'moviles2-e13d3.firebaseapp.com',
    databaseURL: 'https://moviles2-e13d3-default-rtdb.firebaseio.com',
    storageBucket: 'moviles2-e13d3.appspot.com',
    measurementId: 'G-NVYJ7RZZW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtcE7ikLjsKORVVf2uK7Sm8f-4bcutBPU',
    appId: '1:354444862050:android:3978b24290d102e0a8a73b',
    messagingSenderId: '354444862050',
    projectId: 'moviles2-e13d3',
    databaseURL: 'https://moviles2-e13d3-default-rtdb.firebaseio.com',
    storageBucket: 'moviles2-e13d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf-r5JwCqj-3GKRj32QEO6k0VwH5wvqxs',
    appId: '1:354444862050:ios:6e80cb24f6346f71a8a73b',
    messagingSenderId: '354444862050',
    projectId: 'moviles2-e13d3',
    databaseURL: 'https://moviles2-e13d3-default-rtdb.firebaseio.com',
    storageBucket: 'moviles2-e13d3.appspot.com',
    iosBundleId: 'com.example.autonoma1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf-r5JwCqj-3GKRj32QEO6k0VwH5wvqxs',
    appId: '1:354444862050:ios:6e80cb24f6346f71a8a73b',
    messagingSenderId: '354444862050',
    projectId: 'moviles2-e13d3',
    databaseURL: 'https://moviles2-e13d3-default-rtdb.firebaseio.com',
    storageBucket: 'moviles2-e13d3.appspot.com',
    iosBundleId: 'com.example.autonoma1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyDRlwKjKLPypJkF4W5c-ZPtgJG11bJIM',
    appId: '1:354444862050:web:876cf97b25e36b9ca8a73b',
    messagingSenderId: '354444862050',
    projectId: 'moviles2-e13d3',
    authDomain: 'moviles2-e13d3.firebaseapp.com',
    databaseURL: 'https://moviles2-e13d3-default-rtdb.firebaseio.com',
    storageBucket: 'moviles2-e13d3.appspot.com',
    measurementId: 'G-XBPFSEKKEZ',
  );

}